title: "André Staltz"
author: "André Staltz"
description: "Open Source Hacker"
more: "read more"
url: "https://staltz.com"
permalink: none

excerpt_separator: "\n\n\n"
exclude: ["signed_posts", "sign", "sign-all", "verify-all-signed"]
include: [".well-known", "dat.json", "_redirects", "g.txt", "f.txt"]
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
gems:
  - octopress-autoprefixer
  - jekyll-redirect-from
  - jekyll-feed
whitelist:
  - jekyll-redirect-from
